# Generated by Django 2.2.8 on 2020-01-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='yes24_book_id',
            field=models.IntegerField(null=True, verbose_name='Yes24 책 ID'),
        ),
    ]
