# Generated by Django 2.2.7 on 2019-11-23 08:45

from django.db import migrations, models
import django.db.models.deletion
import exercises.models.exercise


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='이름')),
                ('description', models.TextField(verbose_name='설명')),
                ('calorie', models.IntegerField(verbose_name='칼로리')),
                ('power', models.CharField(choices=[('weak', '약함'), ('normal', '보통'), ('strong', '강함')], max_length=255)),
            ],
            options={
                'verbose_name': '운동',
                'verbose_name_plural': '운동들',
            },
        ),
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='이름')),
                ('description', models.TextField(verbose_name='설명')),
            ],
            options={
                'verbose_name': '운동 카테고리',
                'verbose_name_plural': '운동 카테고리들',
            },
        ),
        migrations.CreateModel(
            name='ExerciseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='운동 이름')),
                ('ordering', models.IntegerField(verbose_name='순서')),
                ('url', models.ImageField(upload_to=exercises.models.exercise.image_file_name, verbose_name='이미지')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Exercise', verbose_name='운동')),
            ],
            options={
                'verbose_name': '운동 이미지',
                'verbose_name_plural': '운동 이미지들',
                'ordering': ['ordering'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.ExerciseCategory', verbose_name='카테고리'),
        ),
    ]
