# Generated by Django 2.2.7 on 2019-11-23 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.CreateModel(
            name='ExerciseDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='운동 설명')),
                ('ordering', models.IntegerField(verbose_name='운동 정렬')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.Exercise')),
            ],
            options={
                'verbose_name': '운동 설명',
                'verbose_name_plural': '운동 설명들',
                'ordering': ['ordering'],
            },
        ),
    ]
