# Generated by Django 2.2.7 on 2019-11-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20191123_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='time',
            field=models.IntegerField(default=0, verbose_name='시간'),
            preserve_default=False,
        ),
    ]
