# Generated by Django 2.2.7 on 2019-11-23 07:39

from django.db import migrations, models
import trainers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.ImageField(upload_to=trainers.models.image_file_name)),
                ('impact_image_url', models.ImageField(upload_to=trainers.models.image_file_name)),
            ],
        ),
    ]
