# Generated by Django 2.2.7 on 2019-11-23 16:20

from django.db import migrations, models
import trainers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='이름')),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=trainers.models.image_file_name, verbose_name='트레이너 이미지')),
                ('impact_image_url', models.ImageField(blank=True, null=True, upload_to=trainers.models.image_file_name, verbose_name='트레이너 선택 이미지')),
            ],
            options={
                'verbose_name': '트레이너',
                'verbose_name_plural': '트레이너들',
            },
        ),
    ]
