# Generated by Django 2.2.7 on 2019-11-23 10:13

from django.db import migrations, models
import trainers.models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': '트레이너', 'verbose_name_plural': '트레이너들'},
        ),
        migrations.AlterField(
            model_name='trainer',
            name='image_url',
            field=models.ImageField(upload_to=trainers.models.image_file_name, verbose_name='트레이너 이미지'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='impact_image_url',
            field=models.ImageField(upload_to=trainers.models.image_file_name, verbose_name='트레이너 선택 이미지'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='이름'),
        ),
    ]
